# Generated by Django 5.1.2 on 2024-12-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vineland', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionvineland',
            name='note',
            field=models.TextField(blank=True, help_text='Pour plusieurs lignes, utilisez | comme séparateur', null=True, verbose_name='Note/Indication'),
        ),
        migrations.AlterField(
            model_name='reponsevineland',
            name='reponse',
            field=models.CharField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), ('NSP', 'Ne sais pas'), ('NA', 'Non applicable')], max_length=3, null=True, verbose_name='Réponse'),
        ),
    ]
