# Generated by Django 5.1.2 on 2024-12-03 09:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_alter_sousdomain_domain'),
        ('vineland', '0004_alter_reponsevineland_reponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='EchelleVMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_debut_annee', models.PositiveIntegerField(verbose_name='Âge début - Années')),
                ('age_debut_mois', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(11)], verbose_name='Âge début - Mois')),
                ('age_debut_jour', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(30)], verbose_name='Âge début - Jours')),
                ('age_fin_annee', models.PositiveIntegerField(verbose_name='Âge fin - Années')),
                ('age_fin_mois', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(11)], verbose_name='Âge fin - Mois')),
                ('age_fin_jour', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(30)], verbose_name='Âge fin - Jours')),
                ('note_brute_min', models.PositiveIntegerField(verbose_name='Note brute minimum')),
                ('note_brute_max', models.PositiveIntegerField(verbose_name='Note brute maximum')),
                ('note_echelle_v', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)], verbose_name='Note échelle-V')),
                ('sous_domaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echelle_v_mappings', to='polls.sousdomain', verbose_name='Sous-domaine')),
            ],
            options={
                'verbose_name': 'Correspondance Échelle-V',
                'verbose_name_plural': 'Correspondances Échelle-V',
                'ordering': ['sous_domaine', 'age_debut_annee', 'age_debut_mois', 'note_brute_min'],
                'constraints': [models.CheckConstraint(condition=models.Q(('note_brute_max__gte', models.F('note_brute_min'))), name='note_brute_max_gte_min'), models.CheckConstraint(condition=models.Q(('age_fin_annee__gt', models.F('age_debut_annee')), models.Q(('age_fin_annee', models.F('age_debut_annee')), ('age_fin_mois__gt', models.F('age_debut_mois'))), models.Q(('age_fin_annee', models.F('age_debut_annee')), ('age_fin_mois', models.F('age_debut_mois')), ('age_fin_jour__gte', models.F('age_debut_jour'))), _connector='OR'), name='age_fin_gte_debut')],
            },
        ),
    ]
