# Generated by Django 5.1.2 on 2024-12-04 11:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vineland', '0005_echellevmapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteDomaineVMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tranche_age', models.CharField(choices=[('1-2', '1 à 2 ans'), ('3-6', '3 à 6 ans'), ('7-18', '7 à 18 ans'), ('19-49', '19 à 49 ans'), ('50-90', '50 à 90 ans')], max_length=10, verbose_name="Tranche d'âge")),
                ('communication_min', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(72)], verbose_name='Note Communication minimum')),
                ('communication_max', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(72)], verbose_name='Note Communication maximum')),
                ('vie_quotidienne_min', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(72)], verbose_name='Note Vie quotidienne minimum')),
                ('vie_quotidienne_max', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(72)], verbose_name='Note Vie quotidienne maximum')),
                ('socialisation_min', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(72)], verbose_name='Note Socialisation minimum')),
                ('socialisation_max', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(72)], verbose_name='Note Socialisation maximum')),
                ('motricite_min', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(72)], verbose_name='Note Motricité minimum')),
                ('motricite_max', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(72)], verbose_name='Note Motricité maximum')),
                ('note_standard', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(160)], verbose_name='Note standard')),
                ('note_composite_min', models.PositiveIntegerField(verbose_name='Note composite minimum')),
                ('note_composite_max', models.PositiveIntegerField(verbose_name='Note composite maximum')),
                ('rang_percentile', models.CharField(max_length=10, verbose_name='Rang percentile')),
            ],
            options={
                'verbose_name': 'Correspondance Note Domaine',
                'verbose_name_plural': 'Correspondances Notes Domaines',
                'ordering': ['tranche_age', '-note_standard'],
                'unique_together': {('tranche_age', 'note_standard')},
            },
        ),
    ]
