# Generated by Django 5.1.2 on 2024-12-19 20:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_alter_sousdomain_domain'),
        ('vineland', '0008_niveauadaptatif'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeEquivalentSousDomaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_brute_min', models.IntegerField(verbose_name='Note brute minimum')),
                ('note_brute_max', models.IntegerField(blank=True, null=True, verbose_name='Note brute maximum')),
                ('age_special', models.CharField(blank=True, choices=[('<18', 'Moins de 18 ans'), ('>1', "Plus d'un an")], max_length=4, null=True, verbose_name='Âge spécial')),
                ('age_annees', models.IntegerField(blank=True, null=True, verbose_name='Années')),
                ('age_mois', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(11)], verbose_name='Mois')),
                ('sous_domaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='age_equivalents', to='polls.sousdomain', verbose_name='Sous-domaine')),
            ],
            options={
                'verbose_name': "Équivalence d'âge pour sous-domaine",
                'verbose_name_plural': "Équivalences d'âge pour sous-domaines",
                'ordering': ['sous_domaine', '-age_annees', '-age_mois'],
                'unique_together': {('sous_domaine', 'note_brute_min', 'note_brute_max')},
            },
        ),
    ]
