# Generated by Django 5.1.2 on 2024-12-30 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vineland', '0009_ageequivalentsousdomaine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ageequivalentsousdomaine',
            name='age_special',
            field=models.CharField(blank=True, choices=[('>18', 'Plus de 18 ans'), ('<1', 'Moins de 1 an')], max_length=4, null=True, verbose_name='Âge spécial'),
        ),
    ]
