# Generated by Django 5.1.2 on 2025-02-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vineland', '0010_alter_ageequivalentsousdomaine_age_special'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notedomainevmapping',
            name='note_composite_max',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Note composite maximum'),
        ),
        migrations.AlterField(
            model_name='notedomainevmapping',
            name='note_composite_min',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Note composite minimum'),
        ),
    ]
