# Generated by Django 5.1.2 on 2024-12-01 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polls', '0007_notestandardpercentile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlageItemVineland',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_debut', models.PositiveIntegerField(verbose_name='Premier item de la plage')),
                ('item_fin', models.PositiveIntegerField(verbose_name='Dernier item de la plage')),
                ('age_debut', models.PositiveIntegerField(verbose_name='Âge minimum (en années)')),
                ('age_fin', models.PositiveIntegerField(blank=True, help_text='Laisser vide si pas de maximum (7+ par exemple)', null=True, verbose_name='Âge maximum (en années)')),
                ('sous_domaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plages_items_vineland', to='polls.sousdomain')),
            ],
            options={
                'verbose_name': "Plage d'items Vineland",
                'verbose_name_plural': "Plages d'items Vineland",
                'ordering': ['sous_domaine', 'item_debut'],
            },
        ),
        migrations.CreateModel(
            name='QuestionVineland',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField(verbose_name='Question')),
                ('numero_item', models.PositiveIntegerField(help_text="Numéro de l'item dans le sous-domaine", verbose_name="Numéro de l'item")),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note/Indication')),
                ('permet_na', models.BooleanField(default=False, verbose_name='Permet la réponse N/A')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sous_domaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_vineland', to='polls.sousdomain')),
            ],
            options={
                'verbose_name': 'Question Vineland',
                'verbose_name_plural': 'Questions Vineland',
                'ordering': ['sous_domaine', 'numero_item'],
                'unique_together': {('sous_domaine', 'numero_item')},
            },
        ),
        migrations.CreateModel(
            name='ReponseVineland',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponse', models.CharField(choices=[(0, '0'), (1, '1'), (2, '2'), ('NSP', 'Ne sais pas'), ('NA', 'Non applicable')], max_length=3, verbose_name='Réponse')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='vineland.questionvineland')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses_vineland', to='polls.questionnaire')),
            ],
            options={
                'verbose_name': 'Réponse Vineland',
                'verbose_name_plural': 'Réponses Vineland',
                'unique_together': {('questionnaire', 'question')},
            },
        ),
    ]
