# Generated by Django 5.1.2 on 2024-12-04 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_alter_sousdomain_domain'),
        ('vineland', '0006_notedomainevmapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntervaleConfianceDomaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(choices=[('1', '1 an'), ('2', '2 ans'), ('3', '3 ans'), ('4', '4 ans'), ('5', '5 ans'), ('6', '6 ans'), ('7-8', '7-8 ans'), ('9-11', '9-11 ans'), ('12-14', '12-14 ans'), ('15-18', '15-18 ans'), ('19-29', '19-29 ans'), ('30-49', '30-49 ans'), ('50-90', '50-90 ans')], max_length=10)),
                ('niveau_confiance', models.IntegerField(choices=[(95, '95%'), (90, '90%'), (85, '85%')])),
                ('intervalle', models.IntegerField(help_text="Valeur de l'intervalle (ex: ±5 → entrer 5)")),
                ('note_composite', models.IntegerField(blank=True, help_text='Note composite pour ce niveau de confiance', null=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervalles_confiance', to='polls.domain')),
            ],
            options={
                'verbose_name': 'Intervalle de confiance domaine',
                'verbose_name_plural': 'Intervalles de confiance domaines',
                'ordering': ['age', '-niveau_confiance', 'domain'],
                'unique_together': {('age', 'niveau_confiance', 'domain')},
            },
        ),
        migrations.CreateModel(
            name='IntervaleConfianceSousDomaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(choices=[('1', '1 an'), ('2', '2 ans'), ('3', '3 ans'), ('4', '4 ans'), ('5', '5 ans'), ('6', '6 ans'), ('7-8', '7-8 ans'), ('9-11', '9-11 ans'), ('12-14', '12-14 ans'), ('15-18', '15-18 ans'), ('19-29', '19-29 ans'), ('30-49', '30-49 ans'), ('50-90', '50-90 ans')], max_length=10)),
                ('niveau_confiance', models.IntegerField(choices=[(95, '95%'), (90, '90%'), (85, '85%')])),
                ('intervalle', models.IntegerField(help_text="Valeur de l'intervalle (ex: ±2 → entrer 2)")),
                ('sous_domaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervalles_confiance', to='polls.sousdomain')),
            ],
            options={
                'verbose_name': 'Intervalle de confiance sous-domaine',
                'verbose_name_plural': 'Intervalles de confiance sous-domaines',
                'ordering': ['age', '-niveau_confiance', 'sous_domaine'],
                'unique_together': {('age', 'niveau_confiance', 'sous_domaine')},
            },
        ),
    ]
