# Generated by Django 5.1.2 on 2024-12-19 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vineland', '0007_intervaleconfiancedomaine_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NiveauAdaptatif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(choices=[('faible', 'Faible'), ('assez_faible', 'Assez faible'), ('adapte', 'Adapté'), ('assez_eleve', 'Assez élevé'), ('eleve', 'Élevé')], max_length=20, verbose_name='Niveau adaptatif')),
                ('echelle_v_min', models.IntegerField(verbose_name='Échelle-v minimum')),
                ('echelle_v_max', models.IntegerField(verbose_name='Échelle-v maximum')),
                ('note_standard_min', models.IntegerField(verbose_name='Note standard minimum')),
                ('note_standard_max', models.IntegerField(verbose_name='Note standard maximum')),
            ],
            options={
                'verbose_name': 'Niveau adaptatif',
                'verbose_name_plural': 'Niveaux adaptatifs',
                'ordering': ['echelle_v_min'],
            },
        ),
    ]
