# Generated by Django 5.1.2 on 2025-05-02 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_alter_sousdomain_domain'),
        ('vineland', '0011_alter_notedomainevmapping_note_composite_max_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparaisonDomaineVineland',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=10)),
                ('niveau_significativite', models.CharField(max_length=5)),
                ('difference_requise', models.IntegerField()),
                ('domaine1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparaison_domaine1', to='polls.domain')),
                ('domaine2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparaison_domaine2', to='polls.domain')),
            ],
            options={
                'verbose_name': 'Comparaison de domaines',
                'verbose_name_plural': 'Comparaisons de domaines',
                'unique_together': {('age', 'niveau_significativite', 'domaine1', 'domaine2')},
            },
        ),
        migrations.CreateModel(
            name='ComparaisonSousDomaineVineland',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=10)),
                ('niveau_significativite', models.CharField(max_length=5)),
                ('difference_requise', models.IntegerField()),
                ('sous_domaine1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparaison_sous_domaine1', to='polls.sousdomain')),
                ('sous_domaine2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparaison_sous_domaine2', to='polls.sousdomain')),
            ],
            options={
                'verbose_name': 'Comparaison de sous-domaines',
                'verbose_name_plural': 'Comparaisons de sous-domaines',
                'unique_together': {('age', 'niveau_significativite', 'sous_domaine1', 'sous_domaine2')},
            },
        ),
        migrations.CreateModel(
            name='FrequenceDifferenceDomaineVineland',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=10)),
                ('frequence_16', models.CharField(max_length=10)),
                ('frequence_10', models.CharField(max_length=10)),
                ('frequence_5', models.CharField(max_length=10)),
                ('domaine1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freq_domaine1', to='polls.domain')),
                ('domaine2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freq_domaine2', to='polls.domain')),
            ],
            options={
                'verbose_name': 'Fréquence de différence (domaines)',
                'verbose_name_plural': 'Fréquences de différence (domaines)',
                'unique_together': {('age', 'domaine1', 'domaine2')},
            },
        ),
        migrations.CreateModel(
            name='FrequenceDifferenceSousDomaineVineland',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=10)),
                ('frequence_16', models.CharField(max_length=10)),
                ('frequence_10', models.CharField(max_length=10)),
                ('frequence_5', models.CharField(max_length=10)),
                ('sous_domaine1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freq_sous_domaine1', to='polls.sousdomain')),
                ('sous_domaine2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freq_sous_domaine2', to='polls.sousdomain')),
            ],
            options={
                'verbose_name': 'Fréquence de différence (sous-domaines)',
                'verbose_name_plural': 'Fréquences de différence (sous-domaines)',
                'unique_together': {('age', 'sous_domaine1', 'sous_domaine2')},
            },
        ),
    ]
