# Generated by Django 5.1.2 on 2024-11-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='is_parent',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
