# Generated by Django 5.1.2 on 2024-10-13 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='num_question',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Numéro de la Question'),
        ),
    ]
