# Generated by Django 5.1.2 on 2024-11-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_parent_is_parent_alter_parent_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.FloatField(default='', max_length=255, verbose_name='Nom de l’Élève'),
        ),
    ]
