# Generated by Django 5.1.2 on 2024-11-28 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_agetranche_scoreparametrage_studentscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.FloatField(default=1, verbose_name='Âge'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Nom de l’Élève'),
        ),
    ]
