# Generated by Django 5.1.2 on 2024-11-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_agedeveloppeparametrage'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteStandardPercentile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(choices=[('Communication', 'Communication'), ('Motricité', 'Motricité'), ('Comportements', 'Comportements inadaptés')], max_length=50)),
                ('somme_score_standard', models.CharField(max_length=10)),
                ('rang_percentile', models.CharField(max_length=10)),
            ],
            options={
                'unique_together': {('domain', 'somme_score_standard')},
            },
        ),
    ]
