# Generated by Django 5.1.2 on 2024-12-03 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_notestandardpercentile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sousdomain',
            name='domain',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='sous_domaines', to='polls.domain', verbose_name='Domaine'),
        ),
    ]
