from django.core.management.base import BaseCommand
from ...models import AgeTranche, ScoreParametrage
import json

class Command(BaseCommand):
    help = 'Import parametrage data from JSON files'

    def handle(self, *args, **options):
        # Création de la tranche d'âge
        tranche, created = AgeTranche.objects.get_or_create(
            code='225',
            defaults={
                'label': '2 Ans à 2 ans 5 Mois',
                'min_months': 24,
                'max_months': 29
            }
        )
        self.stdout.write(self.style.SUCCESS(f'Tranche créée: {tranche.label}'))

        # Lecture du fichier JSON
        json_data = """{
            "deuxAnsADeuxAnsCinqMois": [
    {"noteBrute":"0","Titre1":"Domaines de Performance","CVP":{"ns":"6","percentile":"13"},"LE":{"ns":"7","percentile":"17"},"LR":{"ns":"7","percentile":"21"},"MF":{"ns":"3","percentile":"<6"},"MG":{"ns":"4","percentile":"<6"},"IOM":{"ns":"6","percentile":"6"},"EA":{"ns":"6","percentile":"3"},"RS":{"ns":"7","percentile":"18"},"CMC":{"ns":"3","percentile":"<9"},"CVC":{"ns":"6","percentile":"19"},"Titre2":"Rapport de l'Educateur","PC":{"ns":"3","percentile":"<2"},"AP":{"ns":"2","percentile":"<4"},"CA":{"ns":"2","percentile":"1"}},
    {"noteBrute":"1","Titre1":"Domaines de Performance","CVP":{"ns":"6","percentile":"13"},"LE":{"ns":"8","percentile":"40"},"LR":{"ns":"8","percentile":"44"},"MF":{"ns":"3","percentile":"<6"},"MG":{"ns":"5","percentile":"6"},"IOM":{"ns":"7","percentile":"24"},"EA":{"ns":"7","percentile":"16"},"RS":{"ns":"7","percentile":"18"},"CMC":{"ns":"4","percentile":"<9"},"CVC":{"ns":"7","percentile":"38"},"Titre2":"Rapport de l'Educateur","PC":{"ns":"3","percentile":"<2"},"AP":{"ns":"3","percentile":"4"},"CA":{"ns":"2","percentile":"1"}},
    {"noteBrute":"2","Titre1":"Domaines de Performance","CVP":{"ns":"6","percentile":"13"},"LE":{"ns":"9","percentile":"67"},"LR":{"ns":"8","percentile":"44"},"MF":{"ns":"3","percentile":"<6"},"MG":{"ns":"5","percentile":"6"},"IOM":{"ns":"7","percentile":"24"},"EA":{"ns":"7","percentile":"16"},"RS":{"ns":"8","percentile":"38"},"CMC":{"ns":"4","percentile":"<9"},"CVC":{"ns":"7","percentile":"38"},"Titre2":"Rapport de l'Educateur","PC":{"ns":"4","percentile":"2"},"AP":{"ns":"4","percentile":"7"},"CA":{"ns":"3","percentile":"2"}},
    {"noteBrute":"3","Titre1":"Domaines de Performance","CVP":{"ns":"7","percentile":"31"},"LE":{"ns":"9","percentile":"67"},"LR":{"ns":"9","percentile":"53"},"MF":{"ns":"4","percentile":"6"},"MG":{"ns":"5","percentile":"6"},"IOM":{"ns":"8","percentile":"38"},"EA":{"ns":"8","percentile":"34"},"RS":{"ns":"8","percentile":"38"},"CMC":{"ns":"5","percentile":"9"},"CVC":{"ns":"8","percentile":"38"},"Titre2":"Rapport de l'Educateur","PC":{"ns":"4","percentile":"2"},"AP":{"ns":"4","percentile":"7"},"CA":{"ns":"3","percentile":"2"}},
    {"noteBrute":"4","Titre1":"Domaines de Performance","CVP":{"ns":"7","percentile":"31"},"LE":{"ns":"10","percentile":"87"},"LR":{"ns":"9","percentile":"53"},"MF":{"ns":"4","percentile":"6"},"MG":{"ns":"6","percentile":"22"},"IOM":{"ns":"9","percentile":"44"},"EA":{"ns":"8","percentile":"34"},"RS":{"ns":"9","percentile":"50"},"CMC":{"ns":"5","percentile":"9"},"CVC":{"ns":"9","percentile":"44"},"Titre2":"Rapport de l'Educateur","PC":{"ns":"5","percentile":"5"},"AP":{"ns":"5","percentile":"7"},"CA":{"ns":"4","percentile":"5"}},
    {"noteBrute":"5","Titre1":"Domaines de Performance","CVP":{"ns":"7","percentile":"31"},"LE":{"ns":"10","percentile":"87"},"LR":{"ns":"10","percentile":"62"},"MF":{"ns":"4","percentile":"6"},"MG":{"ns":"6","percentile":"22"},"IOM":{"ns":"9","percentile":"44"},"EA":{"ns":"9","percentile":"44"},"RS":{"ns":"9","percentile":"50"},"CMC":{"ns":"5","percentile":"9"},"CVC":{"ns":"9","percentile":"44"},"Titre2":"Rapport de l'Educateur","PC":{"ns":"6","percentile":"8"},"AP":{"ns":"6","percentile":"18"},"CA":{"ns":"4","percentile":"5"}},
    {"noteBrute":"6","Titre1":"Domaines de Performance","CVP":{"ns":"8","percentile":"41"},"LE":{"ns":"11","percentile":"87"},"LR":{"ns":"10","percentile":"62"},"MF":{"ns":"5","percentile":"12"},"MG":{"ns":"7","percentile":"34"},"IOM":{"ns":"10","percentile":"53"},"EA":{"ns":"10","percentile":"50"},"RS":{"ns":"9","percentile":"50"},"CMC":{"ns":"6","percentile":"21"},"CVC":{"ns":"10","percentile":"56"},"Titre2":"Rapport de l'Educateur","PC":{"ns":"6","percentile":"8"},"AP":{"ns":"7","percentile":"32"},"CA":{"ns":"5","percentile":"8"}},
    {"noteBrute":"7","Titre1":"Domaines de Performance","CVP":{"ns":"8","percentile":"41"},"LE":{"ns":"11","percentile":"87"},"LR":{"ns":"11","percentile":"76"},"MF":{"ns":"5","percentile":"12"},"MG":{"ns":"7","percentile":"34"},"IOM":{"ns":"10","percentile":"53"},"EA":{"ns":"10","percentile":"50"},"RS":{"ns":"10","percentile":"59"},"CMC":{"ns":"6","percentile":"21"},"CVC":{"ns":"11","percentile":"63"},"Titre2":"Rapport de l'Educateur","PC":{"ns":"7","percentile":"12"},"AP":{"ns":"8","percentile":"36"},"CA":{"ns":"5","percentile":"8"}},
    {"noteBrute":"8","Titre1":"Domaines de Performance","CVP":{"ns":"8","percentile":"41"},"LE":{"ns":"11","percentile":"87"},"LR":{"ns":"11","percentile":"76"},"MF":{"ns":"6","percentile":"21"},"MG":{"ns":"8","percentile":"38"},"IOM":{"ns":"11","percentile":"62"},"EA":{"ns":"10","percentile":"50"},"RS":{"ns":"10","percentile":"59"},"CMC":{"ns":"7","percentile":"29"},"CVC":{"ns":"11","percentile":"63"},"Titre2":"Rapport de l'Educateur","PC":{"ns":"8","percentile":"17"},"AP":{"ns":"9","percentile":"43"},"CA":{"ns":"6","percentile":"12"}},
    {"noteBrute":"9","Titre1":"Domaines de Performance","CVP":{"ns":"8","percentile":"41"},"LE":{"ns":"12","percentile":"90"},"LR":{"ns":"11","percentile":"76"},"MF":{"ns":"6","percentile":"21"},"MG":{"ns":"8","percentile":"38"},"IOM":{"ns":"12","percentile":"76"},"EA":{"ns":"11","percentile":"72"},"RS":{"ns":"11","percentile":"62"},"CMC":{"ns":"7","percentile":"29"},"CVC":{"ns":"12","percentile":"69"},"Titre2":"Rapport de l'Educateur","PC":{"ns":"9","percentile":"27"},"AP":{"ns":"9","percentile":"43"},"CA":{"ns":"6","percentile":"12"}},
    {"noteBrute":"10","Titre1":"Domaines de Performance","CVP":{"ns":"9","percentile":"53"},"LE":{"ns":"12","percentile":"90"},"LR":{"ns":"12","percentile":"88"},"MF":{"ns":"6","percentile":"21"},"MG":{"ns":"8","percentile":"38"},"IOM":{"ns":"12","percentile":"76"},"EA":{"ns":"11","percentile":"72"},"RS":{"ns":"11","percentile":"62"},"CMC":{"ns":"8","percentile":"38"},"CVC":{"ns":"12","percentile":"69"},"Titre2":"Rapport de l'Educateur","PC":{"ns":"10","percentile":"27"},"AP":{"ns":"10","percentile":"57"},"CA":{"ns":"7","percentile":"20"}},
    {"noteBrute":"11","Titre1":"Domaines de Performance","CVP":{"ns":"9","percentile":"53"},"LE":{"ns":"12","percentile":"90"},"LR":{"ns":"12","percentile":"88"},"MF":{"ns":"7","percentile":"35"},"MG":{"ns":"9","percentile":"50"},"IOM":{"ns":"13","percentile":"91"},"EA":{"ns":"11","percentile":"72"},"RS":{"ns":"12","percentile":"76"},"CMC":{"ns":"8","percentile":"38"},"CVC":{"ns":"13","percentile":"88"},"Titre2":"Rapport de l'Educateur","PC":{"ns":"11","percentile":"37"},"AP":{"ns":"11","percentile":"64"},"CA":{"ns":"7","percentile":"20"}},
    {"noteBrute":"12","Titre1":"Domaines de Performance","CVP":{"ns":"9","percentile":"53"},"LE":{"ns":"13","percentile":"93"},"LR":{"ns":"12","percentile":"88"},"MF":{"ns":"7","percentile":"35"},"MG":{"ns":"9","percentile":"50"},"IOM":{"ns":"13","percentile":"91"},"EA":{"ns":"12","percentile":"88"},"RS":{"ns":"12","percentile":"76"},"CMC":{"ns":"8","percentile":"38"},"CVC":{"ns":"14","percentile":">99"},"Titre2":"Rapport de l'Educateur","PC":{"ns":"11","percentile":"52"},"AP":{"ns":"12","percentile":"64"},"CA":{"ns":"8","percentile":"31"}},
    {"noteBrute":"13","Titre1":"Domaines de Performance","CVP":{"ns":"9","percentile":"53"},"LE":{"ns":"13","percentile":"93"},"LR":{"ns":"12","percentile":"88"},"MF":{"ns":"8","percentile":"41"},"MG":{"ns":"10","percentile":"63"},"IOM":{"ns":"14","percentile":"97"},"EA":{"ns":"12","percentile":"88"},"RS":{"ns":"13","percentile":"94"},"CMC":{"ns":"9","percentile":"41"},"CVC":{"ns":"14","percentile":">99"},"Titre2":"Rapport de l'Educateur","PC":{"ns":"11","percentile":"52"},"AP":{"ns":"13","percentile":"68"},"CA":{"ns":"8","percentile":"31"}},
    {"noteBrute":"14","Titre1":"Domaines de Performance","CVP":{"ns":"10","percentile":"63"},"LE":{"ns":"13","percentile":"93"},"LR":{"ns":"13","percentile":"91"},"MF":{"ns":"8","percentile":"41"},"MG":{"ns":"10","percentile":"63"},"IOM":{"ns":"15","percentile":">99"},"EA":{"ns":"13","percentile":"94"},"RS":{"ns":"13","percentile":"94"},"CMC":{"ns":"9","percentile":"41"},"CVC":{"ns":"15","percentile":">99"},"Titre2":"Rapport de l'Educateur","PC":{"ns":"12","percentile":"75"},"AP":{"ns":"14","percentile":"86"},"CA":{"ns":"9","percentile":"42"}},
    {"noteBrute":"15","Titre1":"Domaines de Performance","CVP":{"ns":"10","percentile":"63"},"LE":{"ns":"14","percentile":"93"},"LR":{"ns":"13","percentile":"91"},"MF":{"ns":"8","percentile":"41"},"MG":{"ns":"11","percentile":"66"},"IOM":{"ns":"15","percentile":">99"},"EA":{"ns":"13","percentile":"94"},"RS":{"ns":"14","percentile":">99"},"CMC":{"ns":"10","percentile":"50"},"CVC":{"ns":"15","percentile":">99"},"Titre2":"Rapport de l'Educateur","PC":{"ns":"12","percentile":"75"},"AP":{"ns":"14","percentile":"86"},"CA":{"ns":"9","percentile":"42"}},
    {"noteBrute":"16","Titre1":"Domaines de Performance","CVP":{"ns":"10","percentile":"63"},"LE":{"ns":"14","percentile":"93"},"LR":{"ns":"13","percentile":"91"},"MF":{"ns":"9","percentile":"41"},"MG":{"ns":"11","percentile":"66"},"IOM":{"ns":"16","percentile":">99"},"EA":{"ns":"14","percentile":">99"},"RS":{"ns":"14","percentile":">99"},"CMC":{"ns":"10","percentile":"50"},"CVC":{"ns":"16","percentile":">99"},"Titre2":"Rapport de l'Educateur","PC":{"ns":"13","percentile":"88"},"AP":{"ns":"15","percentile":">99"},"CA":{"ns":"10","percentile":"50"}},
    {"noteBrute":"17","Titre1":"Domaines de Performance","CVP":{"ns":"11","percentile":"63"},"LE":{"ns":"14","percentile":"93"},"LR":{"ns":"14","percentile":"97"},"MF":{"ns":"9","percentile":"41"},"MG":{"ns":"11","percentile":"66"},"IOM":{"ns":"17","percentile":">99"},"EA":{"ns":"14","percentile":">99"},"RS":{"ns":"14","percentile":">99"},"CMC":{"ns":"10","percentile":"50"},"CVC":{"ns":"16","percentile":">99"},"Titre2":"Rapport de l'Educateur","PC":{"ns":"14","percentile":"93"},"AP":{"ns":"16","percentile":">99"},"CA":{"ns":"10","percentile":"50"}},
    {"noteBrute":"18","Titre1":"Domaines de Performance","CVP":{"ns":"11","percentile":"63"},"LE":{"ns":"15","percentile":"97"},"LR":{"ns":"14","percentile":"97"},"MF":{"ns":"10","percentile":"44"},"MG":{"ns":"12","percentile":"72"},"IOM":{"ns":"17","percentile":">99"},"EA":{"ns":"15","percentile":">99"},"RS":{"ns":"15","percentile":">99"},"CMC":{"ns":"11","percentile":"59"},"CVC":{"ns":"17","percentile":">99"},"Titre2":"Rapport de l'Educateur","PC":{"ns":"14","percentile":"93"},"AP":{"ns":"16","percentile":">99"},"CA":{"ns":"11","percentile":"58"}},
    {"noteBrute":"19","Titre1":"Domaines de Performance","CVP":{"ns":"11","percentile":"63"},"LE":{"ns":"15","percentile":"97"},"LR":{"ns":"14","percentile":"97"},"MF":{"ns":"10","percentile":"44"},"MG":{"ns":"12","percentile":"72"},"IOM":{"ns":"18","percentile":">99"},"EA":{"ns":"15","percentile":">99"},"RS":{"ns":"15","percentile":">99"},"CMC":{"ns":"11","percentile":"59"},"CVC":{"ns":"18","percentile":">99"},"Titre2":"Rapport de l'Educateur","PC":{"ns":"15","percentile":"98"},"AP":{"ns":"17","percentile":">99"},"CA":{"ns":"11","percentile":"58"}},
    {"noteBrute":"20","Titre1":"Domaines de Performance","CVP":{"ns":"11","percentile":"63"},"LE":{"ns":"15","percentile":"97"},"LR":{"ns":"15","percentile":">99"},"MF":{"ns":"10","percentile":"44"},"MG":{"ns":"13","percentile":"78"},"IOM":{"ns":"18","percentile":">99"},"EA":{"ns":"16","percentile":">99"},"RS":{"ns":"15","percentile":">99"},"CMC":{"ns":"12","percentile":"68"},"CVC":{"ns":"18","percentile":">99"},"Titre2":"Rapport de l'Educateur","PC":{"ns":"15","percentile":"98"},"AP":{"ns":"17","percentile":">99"},"CA":{"ns":"12","percentile":"70"}},
    {"noteBrute":"21","Titre1":"Domaines de Performance","CVP":{"ns":"12","percentile":"72"},"LE":{"ns":"15","percentile":"97"},"LR":{"ns":"15","percentile":">99"},"MF":{"ns":"11","percentile":"56"},"MG":{"ns":"13","percentile":"78"},"IOM":{"ns":"-","percentile":"-"},"EA":{"ns":"16","percentile":">99"},"RS":{"ns":"16","percentile":">99"},"CMC":{"ns":"12","percentile":"68"},"CVC":{"ns":"19","percentile":">99"},"Titre2":"Rapport de l'Educateur","PC":{"ns":"-","percentile":"-"},"AP":{"ns":"18","percentile":">90"},"CA":{"ns":"12","percentile":"70"}},
    {"noteBrute":"22","Titre1":"Domaines de Performance","CVP":{"ns":"12","percentile":"72"},"LE":{"ns":"16","percentile":">99"},"LR":{"ns":"15","percentile":">99"},"MF":{"ns":"11","percentile":"56"},"MG":{"ns":"14","percentile":"91"},"IOM":{"ns":"-","percentile":"-"},"EA":{"ns":"17","percentile":">99"},"RS":{"ns":"16","percentile":">99"},"CMC":{"ns":"13","percentile":"85"},"CVC":{"ns":"19","percentile":">99"},"Titre2":"Rapport de l'Educateur","PC":{"ns":"-","percentile":"-"},"AP":{"ns":"18","percentile":">99"},"CA":{"ns":"13","percentile":"80"}},
    {"noteBrute":"23","Titre1":"Domaines de Performance","CVP":{"ns":"12","percentile":"72"},"LE":{"ns":"16","percentile":">99"},"LR":{"ns":"16","percentile":">99"},"MF":{"ns":"11","percentile":"56"},"MG":{"ns":"14","percentile":"91"},"IOM":{"ns":"-","percentile":"-"},"EA":{"ns":"-","percentile":"-"},"RS":{"ns":"17","percentile":">99"},"CMC":{"ns":"13","percentile":"85"},"CVC":{"ns":"-","percentile":"-"},"Titre2":"Rapport de l'Educateur","PC":{"ns":"-","percentile":"-"},"AP":{"ns":"-","percentile":"-"},"CA":{"ns":"19","percentile":">99"}},
    {"noteBrute":"24","Titre1":"Domaines de Performance","CVP":{"ns":"12","percentile":"72"},"LE":{"ns":"16","percentile":">99"},"LR":{"ns":"16","percentile":">99"},"MF":{"ns":"12","percentile":"65"},"MG":{"ns":"14","percentile":"91"},"IOM":{"ns":"-","percentile":"-"},"EA":{"ns":"-","percentile":"-"},"RS":{"ns":"17","percentile":">99"},"CMC":{"ns":"14","percentile":"97"},"CVC":{"ns":"-","percentile":"-"},"Titre2":"Rapport de l'Educateur","PC":{"ns":"-","percentile":"-"},"AP":{"ns":"-","percentile":"-"},"CA":{"ns":"19","percentile":">99"}},
    {"noteBrute":"25","Titre1":"Domaines de Performance","CVP":{"ns":"13","percentile":"88"},"LE":{"ns":"16","percentile":">99"},"LR":{"ns":"16","percentile":">99"},"MF":{"ns":"12","percentile":"65"},"MG":{"ns":"14","percentile":"91"},"IOM":{"ns":"-","percentile":"-"},"EA":{"ns":"-","percentile":"-"},"RS":{"ns":"-","percentile":"-"},"CMC":{"ns":"14","percentile":"97"},"CVC":{"ns":"-","percentile":"-"},"Titre2":"Rapport de l'Educateur","PC":{"ns":"-","percentile":"-"},"AP":{"ns":"20","percentile":">99"},"CA":{"ns":"14","percentile":"89"}},
    {"noteBrute":"26","Titre1":"Domaines de Performance","CVP":{"ns":"13","percentile":"88"},"LE":{"ns":"17","percentile":">99"},"LR":{"ns":"16","percentile":">99"},"MF":{"ns":"13","percentile":"79"},"MG":{"ns":"15","percentile":">99"},"IOM":{"ns":"-","percentile":"-"},"EA":{"ns":"-","percentile":"-"},"RS":{"ns":"-","percentile":"-"},"CMC":{"ns":"15","percentile":">99"},"CVC":{"ns":"-","percentile":"-"},"Titre2":"Rapport de l'Educateur","PC":{"ns":"-","percentile":"-"},"AP":{"ns":"20","percentile":">99"},"CA":{"ns":"14","percentile":"89"}},
    {"noteBrute":"27","Titre1":"Domaines de Performance","CVP":{"ns":"13","percentile":"88"},"LE":{"ns":"17","percentile":">99"},"LR":{"ns":"17","percentile":">99"},"MF":{"ns":"13","percentile":"79"},"MG":{"ns":"15","percentile":">99"},"IOM":{"ns":"-","percentile":"-"},"EA":{"ns":"-","percentile":"-"},"RS":{"ns":"-","percentile":"-"},"CMC":{"ns":"15","percentile":">99"},"CVC":{"ns":"-","percentile":"-"},"Titre2":"Rapport de l'Educateur","PC":{"ns":"-","percentile":"-"},"AP":{"ns":"-","percentile":"-"},"CA":{"ns":"15","percentile":"97"}},
    {"noteBrute":"28","Titre1":"Domaines de Performance","CVP":{"ns":"13","percentile":"88"},"LE":{"ns":"17","percentile":">99"},"LR":{"ns":"17","percentile":">99"},"MF":{"ns":"13","percentile":"79"},"MG":{"ns":"15","percentile":">99"},"IOM":{"ns":"-","percentile":"-"},"EA":{"ns":"-","percentile":"-"},"RS":{"ns":"-","percentile":"-"},"CMC":{"ns":"16","percentile":">99"},"CVC":{"ns":"-","percentile":"-"},"Titre2":"Rapport de l'Educateur","PC":{"ns":"-","percentile":"-"},"AP":{"ns":"-","percentile":"-"},"CA":{"ns":"15","percentile":"97"}},
    {"noteBrute":"29","Titre1":"Domaines de Performance","CVP":{"ns":"13","percentile":"88"},"LE":{"ns":"17","percentile":">99"},"LR":{"ns":"17","percentile":">99"},"MF":{"ns":"14","percentile":"97"},"MG":{"ns":"16","percentile":">99"},"IOM":{"ns":"-","percentile":"-"},"EA":{"ns":"-","percentile":"-"},"RS":{"ns":"-","percentile":"-"},"CMC":{"ns":"16","percentile":">99"},"CVC":{"ns":"-","percentile":"-"},"Titre2":"Rapport de l'Educateur","PC":{"ns":"-","percentile":"-"},"AP":{"ns":"-","percentile":"-"},"CA":{"ns":"16","percentile":">99"}},
    {"noteBrute":"30","Titre1":"Domaines de Performance","CVP":{"ns":"14","percentile":"97"},"LE":{"ns":"18","percentile":">99"},"LR":{"ns":"17","percentile":">99"},"MF":{"ns":"14","percentile":"97"},"MG":{"ns":"16","percentile":">99"},"IOM":{"ns":"-","percentile":"-"},"EA":{"ns":"-","percentile":"-"},"RS":{"ns":"-","percentile":"-"},"CMC":{"ns":"17","percentile":">99"},"CVC":{"ns":"-","percentile":"-"},"Titre2":"Rapport de l'Educateur","PC":{"ns":"-","percentile":"-"},"AP":{"ns":"-","percentile":"-"},"CA":{"ns":"16","percentile":">99"}},
    {"noteBrute":"31","Titre1":"Domaines de Performance","CVP":{"ns":"14","percentile":"97"},"LE":{"ns":"18","percentile":">99"},"LR":{"ns":"18","percentile":">99"},"MF":{"ns":"14","percentile":"97"},"MG":{"ns":"-","percentile":"-"},"IOM":{"ns":"-","percentile":"-"},"EA":{"ns":"-","percentile":"-"},"RS":{"ns":"-","percentile":"-"},"CMC":{"ns":"-","percentile":"-"},"CVC":{"ns":"-","percentile":"-"},"Titre2":"Rapport de l'Educateur","PC":{"ns":"-","percentile":"-"},"AP":{"ns":"-","percentile":"-"},"CA":{"ns":"-","percentile":"-"}},
    {"noteBrute":"32","Titre1":"Domaines de Performance","CVP":{"ns":"14","percentile":"97"},"LE":{"ns":"18","percentile":">99"},"LR":{"ns":"18","percentile":">99"},"MF":{"ns":"15","percentile":">99"},"MG":{"ns":"-","percentile":"-"},"IOM":{"ns":"-","percentile":"-"},"EA":{"ns":"-","percentile":"-"},"RS":{"ns":"-","percentile":"-"},"CMC":{"ns":"-","percentile":"-"},"CVC":{"ns":"-","percentile":"-"},"Titre2":"Rapport de l'Educateur","PC":{"ns":"-","percentile":"-"},"AP":{"ns":"-","percentile":"-"},"CA":{"ns":"-","percentile":"-"}},
    {"noteBrute":"33","Titre1":"Domaines de Performance","CVP":{"ns":"14","percentile":"97"},"LE":{"ns":"18","percentile":">99"},"LR":{"ns":"18","percentile":">99"},"MF":{"ns":"15","percentile":">99"},"MG":{"ns":"-","percentile":"-"},"IOM":{"ns":"-","percentile":"-"},"EA":{"ns":"-","percentile":"-"},"RS":{"ns":"-","percentile":"-"},"CMC":{"ns":"-","percentile":"-"},"CVC":{"ns":"-","percentile":"-"},"Titre2":"Rapport de l'Educateur","PC":{"ns":"-","percentile":"-"},"AP":{"ns":"-","percentile":"-"},"CA":{"ns":"-","percentile":"-"}},
    {"noteBrute":"34","Titre1":"Domaines de Performance","CVP":{"ns":"14","percentile":"97"},"LE":{"ns":"18","percentile":">99"},"LR":{"ns":"19","percentile":">99"},"MF":{"ns":"16","percentile":">99"},"MG":{"ns":"-","percentile":"-"},"IOM":{"ns":"-","percentile":"-"},"EA":{"ns":"-","percentile":"-"},"RS":{"ns":"-","percentile":"-"},"CMC":{"ns":"-","percentile":"-"},"CVC":{"ns":"-","percentile":"-"},"Titre2":"Rapport de l'Educateur","PC":{"ns":"-","percentile":"-"},"AP":{"ns":"-","percentile":"-"},"CA":{"ns":"-","percentile":"-"}},
    {"noteBrute":"35","Titre1":"Domaines de Performance","CVP":{"ns":"15","percentile":">99"},"LE":{"ns":"19","percentile":">99"},"LR":{"ns":"19","percentile":">99"},"MF":{"ns":"16","percentile":">99"},"MG":{"ns":"-","percentile":"-"},"IOM":{"ns":"-","percentile":"-"},"EA":{"ns":"-","percentile":"-"},"RS":{"ns":"-","percentile":"-"},"CMC":{"ns":"-","percentile":"-"},"CVC":{"ns":"-","percentile":"-"},"Titre2":"Rapport de l'Educateur","PC":{"ns":"-","percentile":"-"},"AP":{"ns":"-","percentile":"-"},"CA":{"ns":"-","percentile":"-"}},
    {"noteBrute":"36","Titre1":"Domaines de Performance","CVP":{"ns":"15","percentile":">99"},"LE":{"ns":"19","percentile":">99"},"LR":{"ns":"19","percentile":">99"},"MF":{"ns":"16","percentile":">99"},"MG":{"ns":"-","percentile":"-"},"IOM":{"ns":"-","percentile":"-"},"EA":{"ns":"-","percentile":"-"},"RS":{"ns":"-","percentile":"-"},"CMC":{"ns":"-","percentile":"-"},"CVC":{"ns":"-","percentile":"-"},"Titre2":"Rapport de l'Educateur","PC":{"ns":"-","percentile":"-"},"AP":{"ns":"-","percentile":"-"},"CA":{"ns":"-","percentile":"-"}},
    {"noteBrute":"37","Titre1":"Domaines de Performance","CVP":{"ns":"15","percentile":">99"},"LE":{"ns":"19","percentile":">99"},"LR":{"ns":"20","percentile":">99"},"MF":{"ns":"17","percentile":">99"},"MG":{"ns":"-","percentile":"-"},"IOM":{"ns":"-","percentile":"-"},"EA":{"ns":"-","percentile":"-"},"RS":{"ns":"-","percentile":"-"},"CMC":{"ns":"-","percentile":"-"},"CVC":{"ns":"-","percentile":"-"},"Titre2":"Rapport de l'Educateur","PC":{"ns":"-","percentile":"-"},"AP":{"ns":"-","percentile":"-"},"CA":{"ns":"-","percentile":"-"}},
    {"noteBrute":"38","Titre1":"Domaines de Performance","CVP":{"ns":"15","percentile":">99"},"LE":{"ns":"19","percentile":">99"},"LR":{"ns":"20","percentile":">99"},"MF":{"ns":"17","percentile":">99"},"MG":{"ns":"-","percentile":"-"},"IOM":{"ns":"-","percentile":"-"},"EA":{"ns":"-","percentile":"-"},"RS":{"ns":"-","percentile":"-"},"CMC":{"ns":"-","percentile":"-"},"CVC":{"ns":"-","percentile":"-"},"Titre2":"Rapport de l'Educateur","PC":{"ns":"-","percentile":"-"},"AP":{"ns":"-","percentile":"-"},"CA":{"ns":"-","percentile":"-"}},
    {"noteBrute":"39","Titre1":"Domaines de Performance","CVP":{"ns":"15","percentile":">99"},"LE":{"ns":"20","percentile":">99"},"LR":{"ns":"-","percentile":"-"},"MF":{"ns":"18","percentile":">99"},"MG":{"ns":"-","percentile":"-"},"IOM":{"ns":"-","percentile":"-"},"EA":{"ns":"-","percentile":"-"},"RS":{"ns":"-","percentile":"-"},"CMC":{"ns":"-","percentile":"-"},"CVC":{"ns":"-","percentile":"-"},"Titre2":"Rapport de l'Educateur","PC":{"ns":"-","percentile":"-"},"AP":{"ns":"-","percentile":"-"},"CA":{"ns":"-","percentile":"-"}},
    {"noteBrute":"40","Titre1":"Domaines de Performance","CVP":{"ns":"16","percentile":">99"},"LE":{"ns":"20","percentile":">99"},"LR":{"ns":"-","percentile":"-"},"MF":{"ns":"18","percentile":">99"},"MG":{"ns":"-","percentile":"-"},"IOM":{"ns":"-","percentile":"-"},"EA":{"ns":"-","percentile":"-"},"RS":{"ns":"-","percentile":"-"},"CMC":{"ns":"-","percentile":"-"},"CVC":{"ns":"-","percentile":"-"},"Titre2":"Rapport de l'Educateur","PC":{"ns":"-","percentile":"-"},"AP":{"ns":"-","percentile":"-"},"CA":{"ns":"-","percentile":"-"}},
    {"noteBrute":"41","Titre1":"Domaines de Performance","CVP":{"ns":"16","percentile":">99"},"LE":{"ns":"20","percentile":">99"},"LR":{"ns":"-","percentile":"-"},"MF":{"ns":"-","percentile":"-"},"MG":{"ns":"-","percentile":"-"},"IOM":{"ns":"-","percentile":"-"},"EA":{"ns":"-","percentile":"-"},"RS":{"ns":"-","percentile":"-"},"CMC":{"ns":"-","percentile":"-"},"CVC":{"ns":"-","percentile":"-"},"Titre2":"Rapport de l'Educateur","PC":{"ns":"-","percentile":"-"},"AP":{"ns":"-","percentile":"-"},"CA":{"ns":"-","percentile":"-"}},
    {"noteBrute":"42","Titre1":"Domaines de Performance","CVP":{"ns":"16","percentile":">99"},"LE":{"ns":"20","percentile":">99"},"LR":{"ns":"-","percentile":"-"},"MF":{"ns":"-","percentile":"-"},"MG":{"ns":"-","percentile":"-"},"IOM":{"ns":"-","percentile":"-"},"EA":{"ns":"-","percentile":"-"},"RS":{"ns":"-","percentile":"-"},"CMC":{"ns":"-","percentile":"-"},"CVC":{"ns":"-","percentile":"-"},"Titre2":"Rapport de l'Educateur","PC":{"ns":"-","percentile":"-"},"AP":{"ns":"-","percentile":"-"},"CA":{"ns":"-","percentile":"-"}},
    {"noteBrute":"43","Titre1":"Domaines de Performance","CVP":{"ns":"16","percentile":">99"},"LE":{"ns":"20","percentile":">99"},"LR":{"ns":"-","percentile":"-"},"MF":{"ns":"-","percentile":"-"},"MG":{"ns":"-","percentile":"-"},"IOM":{"ns":"-","percentile":"-"},"EA":{"ns":"-","percentile":"-"},"RS":{"ns":"-","percentile":"-"},"CMC":{"ns":"-","percentile":"-"},"CVC":{"ns":"-","percentile":"-"},"Titre2":"Rapport de l'Educateur","PC":{"ns":"-","percentile":"-"},"AP":{"ns":"-","percentile":"-"},"CA":{"ns":"-","percentile":"-"}},
    {"noteBrute":"44","Titre1":"Domaines de Performance","CVP":{"ns":"17","percentile":">99"},"LE":{"ns":"20","percentile":">99"},"LR":{"ns":"-","percentile":"-"},"MF":{"ns":"-","percentile":"-"},"MG":{"ns":"-","percentile":"-"},"IOM":{"ns":"-","percentile":"-"},"EA":{"ns":"-","percentile":"-"},"RS":{"ns":"-","percentile":"-"},"CMC":{"ns":"-","percentile":"-"},"CVC":{"ns":"-","percentile":"-"},"Titre2":"Rapport de l'Educateur","PC":{"ns":"-","percentile":"-"},"AP":{"ns":"-","percentile":"-"},"CA":{"ns":"-","percentile":"-"}},
    {"noteBrute":"46","Titre1":"Domaines de Performance","CVP":{"ns":"17","percentile":">99"},"LE":{"ns":"20","percentile":">99"},"LR":{"ns":"-","percentile":"-"},"MF":{"ns":"-","percentile":"-"},"MG":{"ns":"-","percentile":"-"},"IOM":{"ns":"-","percentile":"-"},"EA":{"ns":"-","percentile":"-"},"RS":{"ns":"-","percentile":"-"},"CMC":{"ns":"-","percentile":"-"},"CVC":{"ns":"-","percentile":"-"},"Titre2":"Rapport de l'Educateur","PC":{"ns":"-","percentile":"-"},"AP":{"ns":"-","percentile":"-"},"CA":{"ns":"-","percentile":"-"}},
    {"noteBrute":"47","Titre1":"Domaines de Performance","CVP":{"ns":"17","percentile":">99"},"LE":{"ns":"20","percentile":">99"},"LR":{"ns":"-","percentile":"-"},"MF":{"ns":"-","percentile":"-"},"MG":{"ns":"-","percentile":"-"},"IOM":{"ns":"-","percentile":"-"},"EA":{"ns":"-","percentile":"-"},"RS":{"ns":"-","percentile":"-"},"CMC":{"ns":"-","percentile":"-"},"CVC":{"ns":"-","percentile":"-"},"Titre2":"Rapport de l'Educateur","PC":{"ns":"-","percentile":"-"},"AP":{"ns":"-","percentile":"-"},"CA":{"ns":"-","percentile":"-"}},
    {"noteBrute":"48","Titre1":"Domaines de Performance","CVP":{"ns":"18","percentile":">99"},"LE":{"ns":"20","percentile":">99"},"LR":{"ns":"-","percentile":"-"},"MF":{"ns":"-","percentile":"-"},"MG":{"ns":"-","percentile":"-"},"IOM":{"ns":"-","percentile":"-"},"EA":{"ns":"-","percentile":"-"},"RS":{"ns":"-","percentile":"-"},"CMC":{"ns":"-","percentile":"-"},"CVC":{"ns":"-","percentile":"-"},"Titre2":"Rapport de l'Educateur","PC":{"ns":"-","percentile":"-"},"AP":{"ns":"-","percentile":"-"},"CA":{"ns":"-","percentile":"-"}},
    {"noteBrute":"49","Titre1":"Domaines de Performance","CVP":{"ns":"18","percentile":">99"},"LE":{"ns":"20","percentile":">99"},"LR":{"ns":"-","percentile":"-"},"MF":{"ns":"-","percentile":"-"},"MG":{"ns":"-","percentile":"-"},"IOM":{"ns":"-","percentile":"-"},"EA":{"ns":"-","percentile":"-"},"RS":{"ns":"-","percentile":"-"},"CMC":{"ns":"-","percentile":"-"},"CVC":{"ns":"-","percentile":"-"},"Titre2":"Rapport de l'Educateur","PC":{"ns":"-","percentile":"-"},"AP":{"ns":"-","percentile":"-"},"CA":{"ns":"-","percentile":"-"}},
    {"noteBrute":"50","Titre1":"Domaines de Performance","CVP":{"ns":"18","percentile":">99"},"LE":{"ns":"20","percentile":">99"},"LR":{"ns":"-","percentile":"-"},"MF":{"ns":"-","percentile":"-"},"MG":{"ns":"-","percentile":"-"},"IOM":{"ns":"-","percentile":"-"},"EA":{"ns":"-","percentile":"-"},"RS":{"ns":"-","percentile":"-"},"CMC":{"ns":"-","percentile":"-"},"CVC":{"ns":"-","percentile":"-"},"Titre2":"Rapport de l'Educateur","PC":{"ns":"-","percentile":"-"},"AP":{"ns":"-","percentile":"-"},"CA":{"ns":"-","percentile":"-"}},
    {"noteBrute":"51","Titre1":"Domaines de Performance","CVP":{"ns":"18","percentile":">99"},"LE":{"ns":"-","percentile":"-"},"LR":{"ns":"-","percentile":"-"},"MF":{"ns":"-","percentile":"-"},"MG":{"ns":"-","percentile":"-"},"IOM":{"ns":"-","percentile":"-"},"EA":{"ns":"-","percentile":"-"},"RS":{"ns":"-","percentile":"-"},"CMC":{"ns":"-","percentile":"-"},"CVC":{"ns":"-","percentile":"-"},"Titre2":"Rapport de l'Educateur","PC":{"ns":"-","percentile":"-"},"AP":{"ns":"-","percentile":"-"},"CA":{"ns":"-","percentile":"-"}},
    {"noteBrute":"52","Titre1":"Domaines de Performance","CVP":{"ns":"19","percentile":">99"},"LE":{"ns":"-","percentile":"-"},"LR":{"ns":"-","percentile":"-"},"MF":{"ns":"-","percentile":"-"},"MG":{"ns":"-","percentile":"-"},"IOM":{"ns":"-","percentile":"-"},"EA":{"ns":"-","percentile":"-"},"RS":{"ns":"-","percentile":"-"},"CMC":{"ns":"-","percentile":"-"},"CVC":{"ns":"-","percentile":"-"},"Titre2":"Rapport de l'Educateur","PC":{"ns":"-","percentile":"-"},"AP":{"ns":"-","percentile":"-"},"CA":{"ns":"-","percentile":"-"}},
    {"noteBrute":"53","Titre1":"Domaines de Performance","CVP":{"ns":"19","percentile":">99"},"LE":{"ns":"-","percentile":"-"},"LR":{"ns":"-","percentile":"-"},"MF":{"ns":"-","percentile":"-"},"MG":{"ns":"-","percentile":"-"},"IOM":{"ns":"-","percentile":"-"},"EA":{"ns":"-","percentile":"-"},"RS":{"ns":"-","percentile":"-"},"CMC":{"ns":"-","percentile":"-"},"CVC":{"ns":"-","percentile":"-"},"Titre2":"Rapport de l'Educateur","PC":{"ns":"-","percentile":"-"},"AP":{"ns":"-","percentile":"-"},"CA":{"ns":"-","percentile":"-"}},
    {"noteBrute":"54","Titre1":"Domaines de Performance","CVP":{"ns":"19","percentile":">99"},"LE":{"ns":"-","percentile":"-"},"LR":{"ns":"-","percentile":"-"},"MF":{"ns":"-","percentile":"-"},"MG":{"ns":"-","percentile":"-"},"IOM":{"ns":"-","percentile":"-"},"EA":{"ns":"-","percentile":"-"},"RS":{"ns":"-","percentile":"-"},"CMC":{"ns":"-","percentile":"-"},"CVC":{"ns":"-","percentile":"-"},"Titre2":"Rapport de l'Educateur","PC":{"ns":"-","percentile":"-"},"AP":{"ns":"-","percentile":"-"},"CA":{"ns":"-","percentile":"-"}},
    {"noteBrute":"55","Titre1":"Domaines de Performance","CVP":{"ns":"19","percentile":">99"},"LE":{"ns":"-","percentile":"-"},"LR":{"ns":"-","percentile":"-"},"MF":{"ns":"-","percentile":"-"},"MG":{"ns":"-","percentile":"-"},"IOM":{"ns":"-","percentile":"-"},"EA":{"ns":"-","percentile":"-"},"RS":{"ns":"-","percentile":"-"},"CMC":{"ns":"-","percentile":"-"},"CVC":{"ns":"-","percentile":"-"},"Titre2":"Rapport de l'Educateur","PC":{"ns":"-","percentile":"-"},"AP":{"ns":"-","percentile":"-"},"CA":{"ns":"-","percentile":"-"}},
    {"noteBrute":"56","Titre1":"Domaines de Performance","CVP":{"ns":"20","percentile":">99"},"LE":{"ns":"-","percentile":"-"},"LR":{"ns":"-","percentile":"-"},"MF":{"ns":"-","percentile":"-"},"MG":{"ns":"-","percentile":"-"},"IOM":{"ns":"-","percentile":"-"},"EA":{"ns":"-","percentile":"-"},"RS":{"ns":"-","percentile":"-"},"CMC":{"ns":"-","percentile":"-"},"CVC":{"ns":"-","percentile":"-"},"Titre2":"Rapport de l'Educateur","PC":{"ns":"-","percentile":"-"},"AP":{"ns":"-","percentile":"-"},"CA":{"ns":"-","percentile":"-"}},
    {"noteBrute":"57","Titre1":"Domaines de Performance","CVP":{"ns":"20","percentile":">99"},"LE":{"ns":"-","percentile":"-"},"LR":{"ns":"-","percentile":"-"},"MF":{"ns":"-","percentile":"-"},"MG":{"ns":"-","percentile":"-"},"IOM":{"ns":"-","percentile":"-"},"EA":{"ns":"-","percentile":"-"},"RS":{"ns":"-","percentile":"-"},"CMC":{"ns":"-","percentile":"-"},"CVC":{"ns":"-","percentile":"-"},"Titre2":"Rapport de l'Educateur","PC":{"ns":"-","percentile":"-"},"AP":{"ns":"-","percentile":"-"},"CA":{"ns":"-","percentile":"-"}},
    {"noteBrute":"58","Titre1":"Domaines de Performance","CVP":{"ns":"20","percentile":">99"},"LE":{"ns":"-","percentile":"-"},"LR":{"ns":"-","percentile":"-"},"MF":{"ns":"-","percentile":"-"},"MG":{"ns":"-","percentile":"-"},"IOM":{"ns":"-","percentile":"-"},"EA":{"ns":"-","percentile":"-"},"RS":{"ns":"-","percentile":"-"},"CMC":{"ns":"-","percentile":"-"},"CVC":{"ns":"-","percentile":"-"},"Titre2":"Rapport de l'Educateur","PC":{"ns":"-","percentile":"-"},"AP":{"ns":"-","percentile":"-"},"CA":{"ns":"-","percentile":"-"}},
    {"noteBrute":"59","Titre1":"Domaines de Performance","CVP":{"ns":"20","percentile":">99"},"LE":{"ns":"-","percentile":"-"},"LR":{"ns":"-","percentile":"-"},"MF":{"ns":"-","percentile":"-"},"MG":{"ns":"-","percentile":"-"},"IOM":{"ns":"-","percentile":"-"},"EA":{"ns":"-","percentile":"-"},"RS":{"ns":"-","percentile":"-"},"CMC":{"ns":"-","percentile":"-"},"CVC":{"ns":"-","percentile":"-"},"Titre2":"Rapport de l'Educateur","PC":{"ns":"-","percentile":"-"},"AP":{"ns":"-","percentile":"-"},"CA":{"ns":"-","percentile":"-"}},
    {"noteBrute":"60","Titre1":"Domaines de Performance","CVP":{"ns":"20","percentile":">99"},"LE":{"ns":"-","percentile":"-"},"LR":{"ns":"-","percentile":"-"},"MF":{"ns":"-","percentile":"-"},"MG":{"ns":"-","percentile":"-"},"IOM":{"ns":"-","percentile":"-"},"EA":{"ns":"-","percentile":"-"},"RS":{"ns":"-","percentile":"-"},"CMC":{"ns":"-","percentile":"-"},"CVC":{"ns":"-","percentile":"-"},"Titre2":"Rapport de l'Educateur","PC":{"ns":"-","percentile":"-"},"AP":{"ns":"-","percentile":"-"},"CA":{"ns":"-","percentile":"-"}},
    {"noteBrute":"61","Titre1":"Domaines de Performance","CVP":{"ns":"20","percentile":">99"},"LE":{"ns":"-","percentile":"-"},"LR":{"ns":"-","percentile":"-"},"MF":{"ns":"-","percentile":"-"},"MG":{"ns":"-","percentile":"-"},"IOM":{"ns":"-","percentile":"-"},"EA":{"ns":"-","percentile":"-"},"RS":{"ns":"-","percentile":"-"},"CMC":{"ns":"-","percentile":"-"},"CVC":{"ns":"-","percentile":"-"},"Titre2":"Rapport de l'Educateur","PC":{"ns":"-","percentile":"-"},"AP":{"ns":"-","percentile":"-"},"CA":{"ns":"-","percentile":"-"}},
    {"noteBrute":"62","Titre1":"Domaines de Performance","CVP":{"ns":"20","percentile":">99"},"LE":{"ns":"-","percentile":"-"},"LR":{"ns":"-","percentile":"-"},"MF":{"ns":"-","percentile":"-"},"MG":{"ns":"-","percentile":"-"},"IOM":{"ns":"-","percentile":"-"},"EA":{"ns":"-","percentile":"-"},"RS":{"ns":"-","percentile":"-"},"CMC":{"ns":"-","percentile":"-"},"CVC":{"ns":"-","percentile":"-"},"Titre2":"Rapport de l'Educateur","PC":{"ns":"-","percentile":"-"},"AP":{"ns":"-","percentile":"-"},"CA":{"ns":"-","percentile":"-"}},
    {"noteBrute":"63","Titre1":"Domaines de Performance","CVP":{"ns":"20","percentile":">99"},"LE":{"ns":"-","percentile":"-"},"LR":{"ns":"-","percentile":"-"},"MF":{"ns":"-","percentile":"-"},"MG":{"ns":"-","percentile":"-"},"IOM":{"ns":"-","percentile":"-"},"EA":{"ns":"-","percentile":"-"},"RS":{"ns":"-","percentile":"-"},"CMC":{"ns":"-","percentile":"-"},"CVC":{"ns":"-","percentile":"-"},"Titre2":"Rapport de l'Educateur","PC":{"ns":"-","percentile":"-"},"AP":{"ns":"-","percentile":"-"},"CA":{"ns":"-","percentile":"-"}},
    {"noteBrute":"64","Titre1":"Domaines de Performance","CVP":{"ns":"20","percentile":">99"},"LE":{"ns":"-","percentile":"-"},"LR":{"ns":"-","percentile":"-"},"MF":{"ns":"-","percentile":"-"},"MG":{"ns":"-","percentile":"-"},"IOM":{"ns":"-","percentile":"-"},"EA":{"ns":"-","percentile":"-"},"RS":{"ns":"-","percentile":"-"},"CMC":{"ns":"-","percentile":"-"},"CVC":{"ns":"-","percentile":"-"},"Titre2":"Rapport de l'Educateur","PC":{"ns":"-","percentile":"-"},"AP":{"ns":"-","percentile":"-"},"CA":{"ns":"-","percentile":"-"}},
    {"noteBrute":"65","Titre1":"Domaines de Performance","CVP":{"ns":"20","percentile":">99"},"LE":{"ns":"-","percentile":"-"},"LR":{"ns":"-","percentile":"-"},"MF":{"ns":"-","percentile":"-"},"MG":{"ns":"-","percentile":"-"},"IOM":{"ns":"-","percentile":"-"},"EA":{"ns":"-","percentile":"-"},"RS":{"ns":"-","percentile":"-"},"CMC":{"ns":"-","percentile":"-"},"CVC":{"ns":"-","percentile":"-"},"Titre2":"Rapport de l'Educateur","PC":{"ns":"-","percentile":"-"},"AP":{"ns":"-","percentile":"-"},"CA":{"ns":"-","percentile":"-"}},
    {"noteBrute":"66","Titre1":"Domaines de Performance","CVP":{"ns":"20","percentile":">99"},"LE":{"ns":"-","percentile":"-"},"LR":{"ns":"-","percentile":"-"},"MF":{"ns":"-","percentile":"-"},"MG":{"ns":"-","percentile":"-"},"IOM":{"ns":"-","percentile":"-"},"EA":{"ns":"-","percentile":"-"},"RS":{"ns":"-","percentile":"-"},"CMC":{"ns":"-","percentile":"-"},"CVC":{"ns":"-","percentile":"-"},"Titre2":"Rapport de l'Educateur","PC":{"ns":"-","percentile":"-"},"AP":{"ns":"-","percentile":"-"},"CA":{"ns":"-","percentile":"-"}},
    {"noteBrute":"67","Titre1":"Domaines de Performance","CVP":{"ns":"20","percentile":">99"},"LE":{"ns":"-","percentile":"-"},"LR":{"ns":"-","percentile":"-"},"MF":{"ns":"-","percentile":"-"},"MG":{"ns":"-","percentile":"-"},"IOM":{"ns":"-","percentile":"-"},"EA":{"ns":"-","percentile":"-"},"RS":{"ns":"-","percentile":"-"},"CMC":{"ns":"-","percentile":"-"},"CVC":{"ns":"-","percentile":"-"},"Titre2":"Rapport de l'Educateur","PC":{"ns":"-","percentile":"-"},"AP":{"ns":"-","percentile":"-"},"CA":{"ns":"-","percentile":"-"}},
    {"noteBrute":"68","Titre1":"Domaines de Performance","CVP":{"ns":"20","percentile":">99"},"LE":{"ns":"-","percentile":"-"},"LR":{"ns":"-","percentile":"-"},"MF":{"ns":"-","percentile":"-"},"MG":{"ns":"-","percentile":"-"},"IOM":{"ns":"-","percentile":"-"},"EA":{"ns":"-","percentile":"-"},"RS":{"ns":"-","percentile":"-"},"CMC":{"ns":"-","percentile":"-"},"CVC":{"ns":"-","percentile":"-"},"Titre2":"Rapport de l'Educateur","PC":{"ns":"-","percentile":"-"},"AP":{"ns":"-","percentile":"-"},"CA":{"ns":"-","percentile":"-"}}
]
        }"""
        data = json.loads(json_data)['deuxAnsADeuxAnsCinqMois']

        domains = ['CVP', 'LE', 'LR', 'MF', 'MG', 'IOM', 'EA', 'RS', 'CMC', 'CVC']
        count = 0

        for item in data:
            note_brute = item['noteBrute']
            
            for domain in domains:
                if domain in item and item[domain]['ns'] != '-':
                    ScoreParametrage.objects.get_or_create(
                        tranche=tranche,
                        domain='Performance',
                        sous_domain=domain,
                        score_brut=int(note_brute),
                        defaults={
                            'ns': int(item[domain]['ns']),
                            'percentile': item[domain]['percentile']
                        }
                    )
                    count += 1

        self.stdout.write(self.style.SUCCESS(f'{count} paramètres créés'))