name: Build Vineland-II Evaluator

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Permet de lancer manuellement

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Build with PyInstaller (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        python build.py
      
    - name: Build with PyInstaller (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        python build.py
    
    - name: Upload Windows Artifact
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: VinelandII-Evaluator-Windows
        path: dist/VinelandII-Evaluator.exe
        
    - name: Upload macOS Artifact
      if: matrix.os == 'macos-latest'
      uses: actions/upload-artifact@v4
      with:
        name: VinelandII-Evaluator-macOS
        path: dist/VinelandII-Evaluator
        
    - name: Create Release (on tag push)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/VinelandII-Evaluator.exe
          dist/VinelandII-Evaluator
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}